[tool.poetry]
name = "C_RAG"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
langserve = {extras = ["server"], version = ">=0.0.30"}
unstructured = {extras = ["markdown"], version = "^0.14.2"}


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"


[tool.poetry.group.D.dependencies]
ipykernel = "^6.29.4"


[tool.pdm.dev-dependencies]
dev = [
    "langchain-cli>=0.0.15",
]
D = [
    "ipykernel<7.0.0,>=6.29.4",
]

[tool.pdm.build]
includes = ["app"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Your Name", email = "you@example.com"},
]
requires-python = "<3.13,>=3.11"
dependencies = [
    "fastapi[standard]>=0.110.3",
    "annotated-types==0.7.0",
    "anyio==4.6.2.post1",
    "appnope==0.1.4; platform_system == \"Darwin\"",
    "asttokens==2.4.1",
    "certifi==2024.8.30",
    "cffi==1.17.1; implementation_name == \"pypy\"",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "comm==0.2.2",
    "debugpy==1.8.8",
    "decorator==5.1.1",
    "executing==2.1.0",
    "fastapi[standard]==0.110.3",
    "gitdb==4.0.11",
    "gitpython==3.1.43",
    "gritql==0.1.5",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.27.2",
    "idna==3.10",
    "ipykernel==6.29.5",
    "ipython==8.29.0",
    "jedi==0.19.2",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "langchain-cli==0.0.31",
    "langchain-core==0.3.19",
    "langserve[all]==0.3.0",
    "langsmith==0.1.143",
    "markdown-it-py==3.0.0",
    "matplotlib-inline==0.1.7",
    "mdurl==0.1.2",
    "nest-asyncio==1.6.0",
    "orjson==3.10.11",
    "packaging==24.2",
    "parso==0.8.4",
    "pexpect==4.9.0; sys_platform != \"win32\" and sys_platform != \"emscripten\"",
    "platformdirs==4.3.6",
    "prompt-toolkit==3.0.48",
    "psutil==6.1.0",
    "ptyprocess==0.7.0; sys_platform != \"win32\" and sys_platform != \"emscripten\"",
    "pure-eval==0.2.3",
    "pycparser==2.22; implementation_name == \"pypy\"",
    "pydantic==2.9.2",
    "pydantic-core==2.23.4",
    "pygments==2.18.0",
    "python-dateutil==2.9.0.post0",
    "pywin32==308; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pyyaml==6.0.2",
    "pyzmq==26.2.0",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rich==13.9.4",
    "shellingham==1.5.4",
    "six==1.16.0",
    "smmap==5.0.1",
    "sniffio==1.3.1",
    "sse-starlette==1.8.2",
    "stack-data==0.6.3",
    "starlette==0.37.2",
    "tenacity==9.0.0",
    "tomlkit==0.12.5",
    "tornado==6.4.1",
    "traitlets==5.14.3",
    "typer[all]==0.9.4",
    "typing-extensions==4.12.2",
    "urllib3==2.2.3",
    "uvicorn==0.23.2",
    "wcwidth==0.2.13",
]
name = "C_RAG"
version = "0.1.0"
description = ""
readme = "README.md"
