[tool.poetry]
name = "C_RAG"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
langserve = {extras = ["server"], version = ">=0.0.30"}
unstructured = {extras = ["markdown"], version = "^0.14.2"}


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"


[tool.poetry.group.D.dependencies]
ipykernel = "^6.29.4"


[tool.pdm.dev-dependencies]
dev = [
    "langchain-cli>=0.0.15",
]
D = [
    "ipykernel<7.0.0,>=6.29.4",
]

[tool.pdm.build]
includes = ["app"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Your Name", email = "you@example.com"},
]
requires-python = "<3.13,>=3.11"
dependencies = [
    "langserve[server]>=0.0.30",
    "unstructured[markdown]<1.0.0,>=0.14.2",
    "uvicorn>=0.23.2",
    "pydantic>=2.9.2",
    "beautifulsoup4>=4.12.3",
    "langchain-community>=0.3.5",
    "langchainhub>=0.1.21",
    "tavily-python>=0.5.0",
    "pytest>=8.3.3",
    "joblib>=1.4.2",
    "langchain-openai>=0.2.5",
    "langgraph>=0.2.44",
    "langchain-pinecone>=0.2.0",
    "pinecone>=5.3.1",
    "markdown>=3.7",
    "langchain-groq>=0.2.1",
    "pytest-xdist>=3.6.1",
    "python-dotenv>=1.0.1",
    "nbconvert>=7.16.4",
    "langgraph-checkpoint-sqlite>=2.0.1",
    "aiohttp==3.9.5",
    "aiosignal==1.3.1",
    "aiosqlite==0.20.0",
    "annotated-types==0.7.0",
    "anyio==4.6.2.post1",
    "attrs==24.2.0",
    "backoff==2.2.1",
    "beautifulsoup4==4.12.3",
    "bleach==6.2.0",
    "certifi==2024.8.30",
    "cffi==1.17.1; implementation_name == \"pypy\" or platform_python_implementation != \"PyPy\"",
    "chardet==5.2.0",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "cryptography==43.0.3",
    "dataclasses-json==0.6.7",
    "defusedxml==0.7.1",
    "distro==1.9.0",
    "emoji==2.14.0",
    "eval-type-backport==0.2.0",
    "execnet==2.1.1",
    "fastapi==0.115.4",
    "fastjsonschema==2.20.0",
    "filetype==1.2.0",
    "frozenlist==1.5.0",
    "gitdb==4.0.11",
    "gitpython==3.1.43",
    "greenlet==3.1.1; (platform_machine == \"win32\" or platform_machine == \"WIN32\" or platform_machine == \"AMD64\" or platform_machine == \"amd64\" or platform_machine == \"x86_64\" or platform_machine == \"ppc64le\" or platform_machine == \"aarch64\") and python_version < \"3.13\"",
    "gritql==0.1.5",
    "groq==0.11.0",
    "h11==0.14.0",
    "html5lib==1.1",
    "httpcore==1.0.6",
    "httpx==0.27.2",
    "httpx-sse==0.4.0",
    "idna==3.10",
    "iniconfig==2.0.0",
    "jinja2==3.1.4",
    "jiter==0.7.0",
    "joblib==1.4.2",
    "jsonpatch==1.33",
    "jsonpath-python==1.0.6",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyterlab-pygments==0.3.0",
    "langchain==0.3.7",
    "langchain-cli==0.0.31",
    "langchain-community==0.3.5",
    "langchain-core==0.3.15",
    "langchain-groq==0.2.1",
    "langchain-openai==0.2.5",
    "langchain-pinecone==0.2.0",
    "langchain-text-splitters==0.3.2",
    "langchainhub==0.1.21",
    "langdetect==1.0.9",
    "langgraph==0.2.44",
    "langgraph-checkpoint==2.0.2",
    "langgraph-checkpoint-sqlite==2.0.1",
    "langgraph-sdk==0.1.35",
    "langserve[all]==0.3.0",
    "langserve[server]==0.3.0",
    "langsmith==0.1.139",
    "lxml==5.3.0",
    "markdown==3.7",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "marshmallow==3.23.1",
    "mdurl==0.1.2",
    "mistune==3.0.2",
    "msgpack==1.1.0",
    "multidict==6.1.0",
    "mypy-extensions==1.0.0",
    "nbclient==0.10.0",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "nltk==3.9.1",
    "numpy==1.26.4",
    "olefile==0.47",
    "openai==1.53.0",
    "orjson==3.10.11",
    "packaging==24.1",
    "pandocfilters==1.5.1",
    "pinecone==5.3.1",
    "pinecone-client==5.0.1",
    "pinecone-plugin-inference==1.1.0",
    "pinecone-plugin-interface==0.0.7",
    "platformdirs==4.3.6",
    "pluggy==1.5.0",
    "propcache==0.2.0",
    "psutil==6.1.0",
    "pycparser==2.22; implementation_name == \"pypy\" or platform_python_implementation != \"PyPy\"",
    "pydantic==2.9.2",
    "pydantic-core==2.23.4",
    "pydantic-settings==2.6.1",
    "pygments==2.18.0",
    "pypdf==5.1.0",
    "pytest==8.3.3",
    "pytest-xdist==3.6.1",
    "python-dateutil==2.8.2",
    "python-dotenv==1.0.1",
    "python-iso639==2024.10.22",
    "python-magic==0.4.27",
    "python-oxmsg==0.0.1",
    "pywin32==308; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pyyaml==6.0.2",
    "pyzmq==26.2.0",
    "rapidfuzz==3.10.1",
    "referencing==0.35.1",
    "regex==2024.9.11",
    "requests==2.32.3",
    "requests-toolbelt==1.0.0",
    "rich==13.9.4",
    "rpds-py==0.20.1",
    "shellingham==1.5.4",
    "six==1.16.0",
    "smmap==5.0.1",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "sqlalchemy==2.0.35",
    "sse-starlette==1.8.2",
    "starlette==0.41.2",
    "tavily-python==0.5.0",
    "tenacity==9.0.0",
    "tiktoken==0.8.0",
    "tinycss2==1.4.0",
    "tomlkit==0.12.5",
    "tornado==6.4.1",
    "tqdm==4.66.6",
    "traitlets==5.14.3",
    "typer[all]==0.9.4",
    "types-requests==2.32.0.20241016",
    "typing-extensions==4.12.2",
    "typing-inspect==0.9.0",
    "unstructured-client==0.26.2",
    "unstructured[markdown]==0.16.4",
    "urllib3==2.2.3",
    "uvicorn==0.23.2",
    "webencodings==0.5.1",
    "wrapt==1.16.0",
    "yarl==1.17.1",
]
name = "C_RAG"
version = "0.1.0"
description = ""
readme = "README.md"
